name: Verify Build

on:
  push:
    branches: [ "master", "update/2.27.3", "update/2.36.7" ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: pnpm

    - name: Get pnpm
      run: corepack pnpm@10.32.1

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Done
      run: echo "Build verification complete!"